-- Demo data for local development. Applied by `supabase db reset` after migrations.
-- Rules: invented data only — never real client names, emails, or case details.
-- Auth users are not seeded here: register through the app against the local stack,
-- then promote a first admin with the snippet from the auth migration's header.

-- Catalogue demo data (ADM-7). Deliberately uneven, because the list has to
-- render three different states: a service with an archived predecessor so the
-- live version is not simply "the only one", a paused one, and one that has
-- never been published and has no price.
--
-- Two auth users are seeded after all, contrary to the note above: publishing a
-- version requires an assigned lawyer, so a catalogue with no lawyers cannot
-- demonstrate a published service. Nobody logs in as these — they have no
-- password. Register through the app for a usable account.

insert into auth.users (id, email) values
  ('10000000-0000-0000-0000-000000000001', 'olena@example.test'),
  ('10000000-0000-0000-0000-000000000002', 'taras@example.test')
on conflict do nothing;

update public.profiles set full_name = 'Olena Kovalchuk', role = 'lawyer'
where id = '10000000-0000-0000-0000-000000000001';
update public.profiles set full_name = 'Taras Bondarenko', role = 'lawyer'
where id = '10000000-0000-0000-0000-000000000002';

-- Two areas across three services, deliberately: a catalogue where every service
-- sits in the same area cannot demonstrate grouping, and one where each sits in
-- its own cannot demonstrate a group with more than one card in it.
insert into public.services (id, slug, title, summary, practice_area) values
  ('20000000-0000-0000-0000-000000000001', 'divorce-application', 'Divorce application',
   'Application to dissolve a marriage, filed with a district court.', 'family'),
  ('20000000-0000-0000-0000-000000000002', 'alimony-claim', 'Alimony claim',
   'Claim for child maintenance.', 'family'),
  ('20000000-0000-0000-0000-000000000003', 'power-of-attorney', 'Power of attorney',
   'General power of attorney, no legal consequences for the grantor.', 'civil');

-- Olena is accountable for the divorce service and Taras covers it, which is
-- the arrangement the assignment table exists for. power-of-attorney has
-- nobody, so the list has an unassigned row to render.
insert into public.service_assignments (service_id, lawyer_id, is_primary) values
  ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', true),
  ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002', false),
  ('20000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000002', true);

insert into public.service_versions
  (id, service_id, version, generation_mode, review_mode) values
  ('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 1,
   'full_generation', 'lawyer_required'),
  ('30000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001', 2,
   'full_generation', 'lawyer_required'),
  ('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000002', 1,
   'block_assembly', 'lawyer_required');

insert into public.service_version_prices values
  ('30000000-0000-0000-0000-000000000001', 'UAH', 480000),
  ('30000000-0000-0000-0000-000000000002', 'UAH', 520000);

-- Publishing v1 then v2 archives v1, which is the state we want on screen.
update public.service_versions set status = 'published'
where id = '30000000-0000-0000-0000-000000000001';
update public.service_versions set status = 'published'
where id = '30000000-0000-0000-0000-000000000002';

-- svc-alimony keeps its draft, unpriced. svc-poa has no versions at all.

-- Clients and their orders (ADM-62, ADM-63, ADM-66) --------------------------
--
-- No warning about invented people is needed here, and that is the point of the
-- split rather than an oversight in this comment: `clients` has no name column
-- to be careless with. Pseudonyms are generated by the table's own default.
--
-- Deliberately uneven, like the catalogue above, because the list has to render
-- states that differ from each other rather than four rows of the same thing:
-- one order with a reviewer, one in intake with nobody on it, one delivered,
-- and one carrying an Art. 22 request that changes what its state can become.

insert into public.clients (id) values
  ('40000000-0000-0000-0000-000000000001'),
  ('40000000-0000-0000-0000-000000000002');

-- Both one-off, both covering the divorce service, because that is the one with
-- a published version to order from. A delivered order needs coverage that the
-- guard will accept, so these are not decoration.
insert into public.entitlements (id, client_id, kind) values
  ('50000000-0000-0000-0000-000000000001', '40000000-0000-0000-0000-000000000001', 'one_off'),
  ('50000000-0000-0000-0000-000000000002', '40000000-0000-0000-0000-000000000002', 'one_off');

insert into public.entitlement_services (entitlement_id, service_id) values
  ('50000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001'),
  ('50000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001');

-- All against v2, the live version. An order pins the version it was placed
-- against and cannot be moved, so seeding one against the archived v1 would be
-- seeding a state the platform cannot currently produce.
insert into public.orders (id, client_id, service_version_id, entitlement_id) values
  ('60000000-0000-0000-0000-000000000001', '40000000-0000-0000-0000-000000000001',
   '30000000-0000-0000-0000-000000000002', '50000000-0000-0000-0000-000000000001'),
  ('60000000-0000-0000-0000-000000000002', '40000000-0000-0000-0000-000000000002',
   '30000000-0000-0000-0000-000000000002', null),
  ('60000000-0000-0000-0000-000000000003', '40000000-0000-0000-0000-000000000002',
   '30000000-0000-0000-0000-000000000002', '50000000-0000-0000-0000-000000000002'),
  ('60000000-0000-0000-0000-000000000004', '40000000-0000-0000-0000-000000000001',
   '30000000-0000-0000-0000-000000000002', '50000000-0000-0000-0000-000000000001');

-- Walked through the lifecycle rather than inserted at rest, because the guards
-- refuse anything else: an order is created in `intake` and every later state is
-- a transition it has to be allowed to make. That the seed has to do this is the
-- migration working.
update public.orders set status = 'submitted' where id in (
  '60000000-0000-0000-0000-000000000001',
  '60000000-0000-0000-0000-000000000003',
  '60000000-0000-0000-0000-000000000004');
update public.orders set status = 'generating' where id in (
  '60000000-0000-0000-0000-000000000001',
  '60000000-0000-0000-0000-000000000003',
  '60000000-0000-0000-0000-000000000004');

-- With Olena, who is accountable for this service.
update public.orders
set status = 'in_review', reviewer_id = '10000000-0000-0000-0000-000000000001'
where id = '60000000-0000-0000-0000-000000000001';

-- Delivered, which the guard allows only out of review and only against an
-- entitlement that covers the service.
update public.orders
set status = 'in_review', reviewer_id = '10000000-0000-0000-0000-000000000002'
where id = '60000000-0000-0000-0000-000000000003';
update public.orders set status = 'delivered'
where id = '60000000-0000-0000-0000-000000000003';

-- The Art. 22 shape: an order the client asked a human for. Left in
-- `generating`, which is exactly where that request stops it — it cannot reach
-- `delivered` without passing through review.
update public.orders set human_review_requested = true
where id = '60000000-0000-0000-0000-000000000004';

-- 60000000-…-02 keeps its intake: nobody assigned, nothing bought yet.

-- Accounts that can actually sign in, local sandbox only ----------------------
--
-- Here because the alternative was a snippet somebody pastes after every
-- `db reset`, and that snippet has been pasted three times now — the debt was
-- recorded on 2026-08-14 and this is it being paid rather than carried again.
--
-- The lawyers above are seeded without passwords, deliberately: they exist so
-- the catalogue has assignments to render, not so anybody logs in as them. What
-- was missing is a way in at all.
--
-- **This file is applied by `supabase db reset` against the local stack.** These
-- passwords are `sandbox` in plain sight, which is correct for a database that
-- lives in a container on one laptop and is rebuilt from empty on demand, and
-- would be a serious mistake anywhere else. Nothing here runs against the cloud
-- project: `db push` applies migrations and never the seed.

-- The token columns are set to '' rather than left null, and that is the whole
-- reason this insert is longer than it looks like it should be. GoTrue reads
-- them into Go strings, a null does not fit, and what comes back out is
-- `{"code":500,"msg":"Database error querying schema"}` on every sign-in — an
-- error that names the schema and says nothing about the row. Found by calling
-- the auth endpoint directly after the form refused to explain itself.
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
   confirmation_token, recovery_token, email_change, email_change_token_new,
   email_change_token_current, phone_change_token, reauthentication_token)
values
  ('00000000-0000-0000-0000-000000000000', '10000000-0000-0000-0000-00000000000a',
   'authenticated', 'authenticated', 'admin@example.test',
   extensions.crypt('sandbox', extensions.gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"],"role":"admin"}'::jsonb, '{}'::jsonb, now(), now(),
   '', '', '', '', '', '', ''),
  -- A lawyer attached to no service at all, which is the only way to see the
  -- state §4.15 is careful about: an empty list that is the policy rather than
  -- an empty platform. Olena and Taras both cover the divorce service, so
  -- neither of them can show it.
  ('00000000-0000-0000-0000-000000000000', '10000000-0000-0000-0000-00000000000b',
   'authenticated', 'authenticated', 'unattached@example.test',
   extensions.crypt('sandbox', extensions.gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"],"role":"lawyer"}'::jsonb, '{}'::jsonb, now(), now(),
   '', '', '', '', '', '', '')
on conflict (id) do nothing;

update public.profiles set full_name = 'Sandbox Admin', role = 'admin'
where id = '10000000-0000-0000-0000-00000000000a';
update public.profiles set full_name = 'Unattached Lawyer', role = 'lawyer'
where id = '10000000-0000-0000-0000-00000000000b';

-- Olena gets a password too, and the reason is one specific screen.
--
-- The order card renders three entitlement states, and one of them exists only
-- under RLS: a purchase that is *recorded and not readable* (ADR-0019). An
-- admin sees the row; a lawyer sees that there is one and may not read it. To
-- meet that state locally somebody has to sign in as a lawyer who is attached
-- to the service the orders sit on — and Olena is accountable for it, while
-- `unattached@example.test` deliberately is not.
--
-- Her role has to reach `app_metadata` as well as `profiles`: the JWT is what
-- `RequireAuth` and every policy read, and the profile row is the display
-- mirror (ADR-0018).
-- `instance_id` is not decoration: GoTrue filters by it, and a row without one
-- is answered "wrong email or password" no matter how correct the password is.
-- The lawyers above were inserted with an id and an email and nothing else,
-- which was fine while nobody signed in as them.
update auth.users
set instance_id = '00000000-0000-0000-0000-000000000000',
  encrypted_password = extensions.crypt('sandbox', extensions.gen_salt('bf')),
  email_confirmed_at = now(),
  -- Null here fails the same way the token columns do, and just as opaquely:
  -- GoTrue scans both into non-nullable Go values. The lawyers were inserted
  -- with an id and an email, so everything else on the row is null.
  raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb),
  created_at = coalesce(created_at, now()),
  updated_at = now(),
  aud = 'authenticated',
  role = 'authenticated',
  raw_app_meta_data = '{"provider":"email","providers":["email"],"role":"lawyer"}'::jsonb,
  confirmation_token = '',
  recovery_token = '',
  email_change = '',
  email_change_token_new = '',
  email_change_token_current = '',
  phone_change_token = '',
  reauthentication_token = ''
where id = '10000000-0000-0000-0000-000000000001';
