-- Demo data for local development. Applied by `supabase db reset` after migrations.
-- Rules: invented data only — never real client names, emails, or case details.
-- Auth users are not seeded here: register through the app against the local stack,
-- then promote a first admin with the snippet from the auth migration's header.

-- Catalogue demo data (ADM-7). Deliberately uneven, because the list has to
-- render three different states: a service with an archived predecessor so the
-- live version is not simply "the only one", a paused one, and one that has
-- never been published and has no price.
--
-- Two auth users are seeded after all, contrary to the note above: publishing a
-- version requires an assigned lawyer, so a catalogue with no lawyers cannot
-- demonstrate a published service. Nobody logs in as these — they have no
-- password. Register through the app for a usable account.

insert into auth.users (id, email) values
  ('10000000-0000-0000-0000-000000000001', 'olena@example.test'),
  ('10000000-0000-0000-0000-000000000002', 'taras@example.test')
on conflict do nothing;

update public.profiles set full_name = 'Olena Kovalchuk', role = 'lawyer'
where id = '10000000-0000-0000-0000-000000000001';
update public.profiles set full_name = 'Taras Bondarenko', role = 'lawyer'
where id = '10000000-0000-0000-0000-000000000002';

-- Two areas across three services, deliberately: a catalogue where every service
-- sits in the same area cannot demonstrate grouping, and one where each sits in
-- its own cannot demonstrate a group with more than one card in it.
insert into public.services (id, slug, title, summary, practice_area) values
  ('20000000-0000-0000-0000-000000000001', 'divorce-application', 'Divorce application',
   'Application to dissolve a marriage, filed with a district court.', 'family'),
  ('20000000-0000-0000-0000-000000000002', 'alimony-claim', 'Alimony claim',
   'Claim for child maintenance.', 'family'),
  ('20000000-0000-0000-0000-000000000003', 'power-of-attorney', 'Power of attorney',
   'General power of attorney, no legal consequences for the grantor.', 'civil');

-- Olena is accountable for the divorce service and Taras covers it, which is
-- the arrangement the assignment table exists for. power-of-attorney has
-- nobody, so the list has an unassigned row to render.
insert into public.service_assignments (service_id, lawyer_id, is_primary) values
  ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', true),
  ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002', false),
  ('20000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000002', true);

insert into public.service_versions
  (id, service_id, version, generation_mode, review_mode) values
  ('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 1,
   'full_generation', 'lawyer_required'),
  ('30000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001', 2,
   'full_generation', 'lawyer_required'),
  ('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000002', 1,
   'block_assembly', 'lawyer_required');

insert into public.service_version_prices values
  ('30000000-0000-0000-0000-000000000001', 'UAH', 480000),
  ('30000000-0000-0000-0000-000000000002', 'UAH', 520000);

-- Publishing v1 then v2 archives v1, which is the state we want on screen.
update public.service_versions set status = 'published'
where id = '30000000-0000-0000-0000-000000000001';
update public.service_versions set status = 'published'
where id = '30000000-0000-0000-0000-000000000002';

-- svc-alimony keeps its draft, unpriced. svc-poa has no versions at all.

-- Clients and their orders (ADM-62, ADM-63, ADM-66) --------------------------
--
-- No warning about invented people is needed here, and that is the point of the
-- split rather than an oversight in this comment: `clients` has no name column
-- to be careless with. Pseudonyms are generated by the table's own default.
--
-- Deliberately uneven, like the catalogue above, because the list has to render
-- states that differ from each other rather than four rows of the same thing:
-- one order with a reviewer, one in intake with nobody on it, one delivered,
-- and one carrying an Art. 22 request that changes what its state can become.

insert into public.clients (id) values
  ('40000000-0000-0000-0000-000000000001'),
  ('40000000-0000-0000-0000-000000000002');

-- Both one-off, both covering the divorce service, because that is the one with
-- a published version to order from. A delivered order needs coverage that the
-- guard will accept, so these are not decoration.
insert into public.entitlements (id, client_id, kind) values
  ('50000000-0000-0000-0000-000000000001', '40000000-0000-0000-0000-000000000001', 'one_off'),
  ('50000000-0000-0000-0000-000000000002', '40000000-0000-0000-0000-000000000002', 'one_off');

insert into public.entitlement_services (entitlement_id, service_id) values
  ('50000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001'),
  ('50000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001');

-- All against v2, the live version. An order pins the version it was placed
-- against and cannot be moved, so seeding one against the archived v1 would be
-- seeding a state the platform cannot currently produce.
insert into public.orders (id, client_id, service_version_id, entitlement_id) values
  ('60000000-0000-0000-0000-000000000001', '40000000-0000-0000-0000-000000000001',
   '30000000-0000-0000-0000-000000000002', '50000000-0000-0000-0000-000000000001'),
  ('60000000-0000-0000-0000-000000000002', '40000000-0000-0000-0000-000000000002',
   '30000000-0000-0000-0000-000000000002', null),
  ('60000000-0000-0000-0000-000000000003', '40000000-0000-0000-0000-000000000002',
   '30000000-0000-0000-0000-000000000002', '50000000-0000-0000-0000-000000000002'),
  ('60000000-0000-0000-0000-000000000004', '40000000-0000-0000-0000-000000000001',
   '30000000-0000-0000-0000-000000000002', '50000000-0000-0000-0000-000000000001');

-- Walked through the lifecycle rather than inserted at rest, because the guards
-- refuse anything else: an order is created in `intake` and every later state is
-- a transition it has to be allowed to make. That the seed has to do this is the
-- migration working.
update public.orders set status = 'submitted' where id in (
  '60000000-0000-0000-0000-000000000001',
  '60000000-0000-0000-0000-000000000003',
  '60000000-0000-0000-0000-000000000004');
update public.orders set status = 'generating' where id in (
  '60000000-0000-0000-0000-000000000001',
  '60000000-0000-0000-0000-000000000003',
  '60000000-0000-0000-0000-000000000004');

-- With Olena, who is accountable for this service.
update public.orders
set status = 'in_review', reviewer_id = '10000000-0000-0000-0000-000000000001'
where id = '60000000-0000-0000-0000-000000000001';

-- Delivered, which the guard allows only out of review and only against an
-- entitlement that covers the service.
update public.orders
set status = 'in_review', reviewer_id = '10000000-0000-0000-0000-000000000002'
where id = '60000000-0000-0000-0000-000000000003';
update public.orders set status = 'delivered'
where id = '60000000-0000-0000-0000-000000000003';

-- The Art. 22 shape: an order the client asked a human for. Left in
-- `generating`, which is exactly where that request stops it — it cannot reach
-- `delivered` without passing through review.
update public.orders set human_review_requested = true
where id = '60000000-0000-0000-0000-000000000004';

-- 60000000-…-02 keeps its intake: nobody assigned, nothing bought yet.

-- Accounts that can actually sign in, local sandbox only ----------------------
--
-- Here because the alternative was a snippet somebody pastes after every
-- `db reset`, and that snippet has been pasted three times now — the debt was
-- recorded on 2026-08-14 and this is it being paid rather than carried again.
--
-- The lawyers above are seeded without passwords, deliberately: they exist so
-- the catalogue has assignments to render, not so anybody logs in as them. What
-- was missing is a way in at all.
--
-- **This file is applied by `supabase db reset` against the local stack.** These
-- passwords are `sandbox` in plain sight, which is correct for a database that
-- lives in a container on one laptop and is rebuilt from empty on demand, and
-- would be a serious mistake anywhere else. Nothing here runs against the cloud
-- project: `db push` applies migrations and never the seed.

-- The token columns are set to '' rather than left null, and that is the whole
-- reason this insert is longer than it looks like it should be. GoTrue reads
-- them into Go strings, a null does not fit, and what comes back out is
-- `{"code":500,"msg":"Database error querying schema"}` on every sign-in — an
-- error that names the schema and says nothing about the row. Found by calling
-- the auth endpoint directly after the form refused to explain itself.
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
   confirmation_token, recovery_token, email_change, email_change_token_new,
   email_change_token_current, phone_change_token, reauthentication_token)
values
  ('00000000-0000-0000-0000-000000000000', '10000000-0000-0000-0000-00000000000a',
   'authenticated', 'authenticated', 'admin@example.test',
   extensions.crypt('sandbox', extensions.gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"],"role":"admin"}'::jsonb, '{}'::jsonb, now(), now(),
   '', '', '', '', '', '', ''),
  -- A lawyer attached to no service at all, which is the only way to see the
  -- state §4.15 is careful about: an empty list that is the policy rather than
  -- an empty platform. Olena and Taras both cover the divorce service, so
  -- neither of them can show it.
  ('00000000-0000-0000-0000-000000000000', '10000000-0000-0000-0000-00000000000b',
   'authenticated', 'authenticated', 'unattached@example.test',
   extensions.crypt('sandbox', extensions.gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"],"role":"lawyer"}'::jsonb, '{}'::jsonb, now(), now(),
   '', '', '', '', '', '', '')
on conflict (id) do nothing;

update public.profiles set full_name = 'Sandbox Admin', role = 'admin'
where id = '10000000-0000-0000-0000-00000000000a';
update public.profiles set full_name = 'Unattached Lawyer', role = 'lawyer'
where id = '10000000-0000-0000-0000-00000000000b';

-- Olena gets a password too, and the reason is one specific screen.
--
-- The order card renders three entitlement states, and one of them exists only
-- under RLS: a purchase that is *recorded and not readable* (ADR-0019). An
-- admin sees the row; a lawyer sees that there is one and may not read it. To
-- meet that state locally somebody has to sign in as a lawyer who is attached
-- to the service the orders sit on — and Olena is accountable for it, while
-- `unattached@example.test` deliberately is not.
--
-- Her role has to reach `app_metadata` as well as `profiles`: the JWT is what
-- `RequireAuth` and every policy read, and the profile row is the display
-- mirror (ADR-0018).
-- `instance_id` is not decoration: GoTrue filters by it, and a row without one
-- is answered "wrong email or password" no matter how correct the password is.
-- The lawyers above were inserted with an id and an email and nothing else,
-- which was fine while nobody signed in as them.
update auth.users
set instance_id = '00000000-0000-0000-0000-000000000000',
  encrypted_password = extensions.crypt('sandbox', extensions.gen_salt('bf')),
  email_confirmed_at = now(),
  -- Null here fails the same way the token columns do, and just as opaquely:
  -- GoTrue scans both into non-nullable Go values. The lawyers were inserted
  -- with an id and an email, so everything else on the row is null.
  raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb),
  created_at = coalesce(created_at, now()),
  updated_at = now(),
  aud = 'authenticated',
  role = 'authenticated',
  raw_app_meta_data = '{"provider":"email","providers":["email"],"role":"lawyer"}'::jsonb,
  confirmation_token = '',
  recovery_token = '',
  email_change = '',
  email_change_token_new = '',
  email_change_token_current = '',
  phone_change_token = '',
  reauthentication_token = ''
where id = '10000000-0000-0000-0000-000000000001';

-- Law norm register (ADM-46). The register was the one screen a fresh sandbox
-- could not demonstrate: the tables ship empty, so `/law` rendered its empty
-- state and the two badges §9.10 exists for were never both on screen.
--
-- Timestamps are relative to `now()` rather than fixed dates, because freshness
-- is a comparison against the clock. A seed with absolute dates demonstrates
-- "stale" for a week and then demonstrates it for everything.
--
-- Inserted with the default 7-day cadence and re-timed further down, and the
-- order is not cosmetic: `recommended_probe_interval` answers 7 days while a
-- norm carries no references, so a 1-day interval chosen *here* would be asked
-- for a reason it does not owe. The references come first, the recommendation
-- moves, and only then does the cadence.
insert into public.law_norms
  (id, source, act_id, act_title, scope, article, act_scope_reason,
   source_url, canonical_url, state, fingerprint,
   last_checked_at, last_verified_at, created_at, updated_at)
values
  -- Verified and fresh: checked half a day ago, nothing moved.
  ('70000000-0000-0000-0000-000000000001', 'zakon_rada', '2947-14',
   'Сімейний кодекс України', 'article', '105', null,
   'https://zakon.rada.gov.ua/laws/show/2947-14/ed20240101#n800',
   'https://zakon.rada.gov.ua/laws/show/2947-14',
   'verified', 'sha256:98d06bbe0824bb327c56dcf4e7bdd24c07eb29f82ccb6b9468f223c8310cd9ea',
   now() - interval '12 hours', now() - interval '12 hours',
   now() - interval '49 days', now() - interval '12 hours'),

  -- Verified and *stale*, which is the pair the whole of §9.10 is about: the
  -- last thing we heard was "no difference", and we have not heard anything
  -- since. A register with one badge per row would show this one green.
  ('70000000-0000-0000-0000-000000000002', 'zakon_rada', '2947-14',
   'Сімейний кодекс України', 'article', '180', null,
   'https://zakon.rada.gov.ua/laws/show/2947-14',
   'https://zakon.rada.gov.ua/laws/show/2947-14',
   'verified', 'sha256:4b4a2c774db41663751dae997124d7a1c8c644f2bd21b369406097d1fbdafaf6',
   now() - interval '30 days', now() - interval '30 days',
   now() - interval '49 days', now() - interval '30 days'),

  -- Scope `act`, so the article is null and the reason is not (§9.4).
  ('70000000-0000-0000-0000-000000000003', 'zakon_rada', '435-15',
   'Цивільний кодекс України', 'act', null,
   'The template rests on the act as a whole; noise expected.',
   'https://zakon.rada.gov.ua/laws/show/435-15',
   'https://zakon.rada.gov.ua/laws/show/435-15',
   'unverified', null,
   null, null, now() - interval '40 days', now() - interval '40 days'),

  -- Entered and never fetched: neutral state, neutral freshness. Today this is
  -- every norm's state, which is why the register has to render it well.
  ('70000000-0000-0000-0000-000000000004', 'zakon_rada', '1618-15',
   'Цивільний процесуальний кодекс України', 'article', '116', null,
   'https://zakon.rada.gov.ua/laws/show/1618-15',
   'https://zakon.rada.gov.ua/laws/show/1618-15',
   'unverified', null,
   null, null, now() - interval '17 days', now() - interval '17 days'),

  -- Drifted, and deliberately *fresh*: something moved two hours ago and nobody
  -- has read it yet. The state badge is the alarm and the freshness badge is
  -- green — two claims, and neither one implies the other.
  ('70000000-0000-0000-0000-000000000005', 'zakon_rada', '1404-19',
   'Про виконавче провадження', 'article', '26', null,
   'https://zakon.rada.gov.ua/laws/show/1404-19',
   'https://zakon.rada.gov.ua/laws/show/1404-19',
   'drifted', 'sha256:d7b95f2dcf97be346d42f56ca49299d750883724a1ed24bd95f737f01b7cf8fe',
   now() - interval '2 hours', now() - interval '20 hours',
   now() - interval '26 days', now() - interval '2 hours')
on conflict (id) do nothing;

-- Which service rests on which norm, and for what (§9.5.6).
--
-- `power-of-attorney` is deliberately absent: a service with no law references
-- at all is the state every service is in before somebody enters the first one,
-- and the empty tab needs a service that produces it. Article 105 carries two
-- dependents, because §9.3's point — the register is shared, and a cadence
-- changed on one row is changed for every service in the last column — is
-- invisible on a register where every norm serves exactly one service.
insert into public.service_law_refs (id, service_id, norm_id, relied_on, created_at, updated_at)
values
  ('80000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001',
   '70000000-0000-0000-0000-000000000001',
   'Grounds on which a marriage may be dissolved by a court.',
   now() - interval '49 days', now() - interval '49 days'),
  ('80000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001',
   '70000000-0000-0000-0000-000000000004',
   'Which court the application is filed with.',
   now() - interval '17 days', now() - interval '17 days'),
  ('80000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000001',
   '70000000-0000-0000-0000-000000000005',
   'Enforcement of the maintenance order once the decree is granted.',
   now() - interval '26 days', now() - interval '26 days'),
  ('80000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000002',
   '70000000-0000-0000-0000-000000000001',
   'Dissolution is the ground the maintenance claim follows from.',
   now() - interval '37 days', now() - interval '37 days'),
  ('80000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000002',
   '70000000-0000-0000-0000-000000000002',
   'The parents'' duty to maintain a child until majority.',
   now() - interval '37 days', now() - interval '37 days'),
  ('80000000-0000-0000-0000-000000000006', '20000000-0000-0000-0000-000000000002',
   '70000000-0000-0000-0000-000000000003',
   'General obligations law, relied on throughout the template.',
   now() - interval '37 days', now() - interval '37 days')
on conflict (id) do nothing;

-- Now the cadences. Articles 105 and 26 sit behind the published divorce
-- service, so `recommended_probe_interval` already says one day and the guard
-- asks for no reason. Article 116 is faster than the recommendation, which is a
-- choice, and §9.8 records a choice with its reason. The two norms left alone
-- keep the 7-day default: nothing on sale depends on them yet.
update public.law_norms set probe_interval = interval '1 day'
where id in ('70000000-0000-0000-0000-000000000001', '70000000-0000-0000-0000-000000000005');

update public.law_norms
set probe_interval = interval '12 hours',
  interval_reason = 'Amended twice during the procedural reform.'
where id = '70000000-0000-0000-0000-000000000004';

-- What those articles said (§9.7, ADM-43). Every other domain table is seeded
-- and this one would have shipped empty, which is how `document_blocks` earned
-- its line in `docs/STATE.md` a session ago.
--
-- **The wording is illustrative, not the actual text of these articles.** A
-- fixture that reads as authoritative law is worse than one that plainly does
-- not, because somebody eventually quotes it. What is real here is the shape:
-- normalized as `normalizeArticleText` leaves it — single spaces, a blank line
-- between paragraphs, no trailing space — and fingerprinted with the sha256 the
-- normalizer would actually produce over these bytes. So the register's
-- fingerprints and this table agree by construction rather than by assertion,
-- and `law_norms_adopt_revision` is a no-op on load instead of a surprise.
--
-- Article 26 carries two revisions, and that pair is the reason the table is
-- seeded at all: it is the only fixture from which a diff can be produced. The
-- norm is `drifted` — something moved two hours ago and nobody has read it yet
-- — so triage has an old wording and a new one to put side by side, which is
-- exactly what §9.16 gives a lawyer one business day to do. A register holding
-- only current text can render that state and not the work it implies.
insert into public.law_norm_revisions
  (id, norm_id, fingerprint, normalizer_version, content,
   published_revision_date, observed_at, created_at)
values
  ('90000000-0000-0000-0000-000000000001', '70000000-0000-0000-0000-000000000001',
   'sha256:98d06bbe0824bb327c56dcf4e7bdd24c07eb29f82ccb6b9468f223c8310cd9ea', 1,
   'Шлюб припиняється внаслідок його розірвання за рішенням суду за заявою одного з подружжя.

Суд постановляє рішення про розірвання шлюбу, якщо буде встановлено, що подальше спільне життя подружжя суперечить інтересам одного з них.',
   date '2024-01-01', now() - interval '49 days', now() - interval '49 days'),

  ('90000000-0000-0000-0000-000000000002', '70000000-0000-0000-0000-000000000002',
   'sha256:4b4a2c774db41663751dae997124d7a1c8c644f2bd21b369406097d1fbdafaf6', 1,
   'Батьки зобов''язані утримувати дитину до досягнення нею повноліття.',
   date '2023-06-15', now() - interval '49 days', now() - interval '49 days'),

  -- The wording before the amendment. Still here, which is the entire point.
  ('90000000-0000-0000-0000-000000000003', '70000000-0000-0000-0000-000000000005',
   'sha256:9cdbe59b4f2dc6f3e6f4daa841327f5cb54f2002826b50bc0b4c2aa7e0089c90', 1,
   'Виконавець розпочинає виконавче провадження на підставі виконавчого документа за заявою стягувача.

Заява подається у письмовій формі.',
   date '2023-11-20', now() - interval '26 days', now() - interval '26 days'),

  -- And what it says now: one clause widened, and the inline footnote that
  -- announces it. Both survive normalization on purpose — the footnote appearing
  -- is the event being watched for, not noise to be stripped.
  ('90000000-0000-0000-0000-000000000004', '70000000-0000-0000-0000-000000000005',
   'sha256:d7b95f2dcf97be346d42f56ca49299d750883724a1ed24bd95f737f01b7cf8fe', 1,
   'Виконавець розпочинає виконавче провадження на підставі виконавчого документа за заявою стягувача.

Заява подається у письмовій або електронній формі.

{ Частину другу викладено в новій редакції згідно із Законом N 1404-19 }',
   date '2026-08-01', now() - interval '2 hours', now() - interval '2 hours')
on conflict (id) do nothing;

-- The queue a lawyer opens (§9.11, §9.16, ADM-46).
--
-- Exactly one row, for the one norm seeded as `drifted` — because `drifted`
-- means "the fingerprint moved and nobody has looked yet", and a norm in that
-- state with nothing waiting to be looked at is a state that rests on nothing.
-- The two revisions above are what it pairs, which is the only pair in this file
-- from which a diff can actually be rendered.
--
-- Left `open` rather than resolved, so the triage screen has the state it exists
-- to render. The four seeded norms that are not drifting have no signal, which is
-- the other half: a queue that is never empty is a queue nobody trusts.
insert into public.law_signals
  (id, norm_id, cause, revision_id, previous_revision_id, raised_at, state, created_at, updated_at)
values
  ('a0000000-0000-0000-0000-000000000001', '70000000-0000-0000-0000-000000000005',
   'drifted',
   '90000000-0000-0000-0000-000000000004',
   '90000000-0000-0000-0000-000000000003',
   now() - interval '2 hours', 'open',
   now() - interval '2 hours', now() - interval '2 hours')
on conflict (id) do nothing;

-- Questionnaire fields (ADM-18, ADM-19). Same reason the norms above are here:
-- the tables ship empty, so `/services/:id/fields` rendered its empty state and
-- the GDPR column — the half ADM-19 exists for — was never on screen at all.
--
-- Four fields on one service, chosen for the states the screen has to tell
-- apart rather than for realism: one carrying personal data with an Art. 6
-- basis, one carrying nothing, one `select` with its choices, and one carrying
-- an Art. 9 special category on top of the Art. 6 basis. The second service
-- keeps a single field so the "one field" plural form is reachable, and
-- power-of-attorney keeps none, so the honest empty state is still reachable
-- too.
--
-- Every row satisfies the triad in both directions, because a seed that held a
-- flag without its basis would not be a seed — Postgres would refuse it.
insert into public.questionnaire_fields
  (id, service_id, key, label, help_text, field_type, required, position, options,
   is_personal_data, legal_basis, retention_days,
   is_special_category, special_category_basis)
values
  ('40000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001',
   'applicant_name', 'Прізвище, імʼя та по батькові позивача',
   'Так, як записано в паспорті.', 'text', true, 0, null,
   true, 'contract', 1095, false, null),

  ('40000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001',
   'marriage_date', 'Дата реєстрації шлюбу', null, 'date', true, 1, null,
   false, null, null, false, null),

  ('40000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000001',
   'court_region', 'Область суду', null, 'select', true, 2,
   '["Київська", "Львівська", "Одеська"]'::jsonb,
   false, null, null, false, null),

  -- The Art. 9 row. `legal_claims` is the basis that carries most of the weight
  -- on this platform, and the point of seeding it is that the screen renders
  -- two badges here rather than one.
  ('40000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000001',
   'health_grounds', 'Обставини здоровʼя, на які спирається позов',
   'Лише якщо позов справді на них спирається.', 'long_text', false, 3, null,
   true, 'legitimate_interests', 1095, true, 'legal_claims'),

  ('40000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000002',
   'monthly_amount', 'Щомісячна сума, яку стягують', null, 'number', true, 0, null,
   false, null, null, false, null);
