// What a Supabase auth failure says to the person who caused it.
//
// The rule this file exists to hold: match on `AuthError.code`, never on
// `error.message`. The message is English prose generated by the auth server
// and reworded between releases without notice, so a `message.includes(…)`
// translation is one that silently stops working on an upgrade — and stops
// working by falling back to English, which is the failure nobody reports.
//
// It lives beside the two screens rather than in `shared/` because it is about
// the auth client, which only `src/app/` talks to. `shared/api/errors.ts` is
// the other half of the same idea for `AppError`, and the two are deliberately
// separate: one closed set of codes belongs to this repository, the other to a
// vendor, and merging them would make a vendor's release note a change to our
// error model.

import type { TranslationKey } from "@legal-ai/i18n";

/**
 * `code` is `string | undefined` rather than the vendor's `ErrorCode` union on
 * purpose. It is typed `ErrorCode | (string & {}) | undefined` upstream — a
 * widened union, so it already admits codes this switch has never heard of, and
 * every one of them has to land on the caller's fallback.
 *
 * The fallback is an argument because "could not sign you in" and "could not
 * create the account" are different sentences, and a screen that borrows the
 * other one tells the reader about an action they did not take.
 */
export function authErrorKey(code: string | undefined, fallback: TranslationKey): TranslationKey {
  switch (code) {
    case "invalid_credentials":
      return "auth.error.invalidCredentials";
    case "email_not_confirmed":
      return "auth.error.emailNotConfirmed";
    case "email_exists":
    case "user_already_exists":
      return "auth.error.emailExists";
    case "weak_password":
      return "auth.error.weakPassword";
    case "over_email_send_rate_limit":
      return "auth.error.rateLimited";
    case "signup_disabled":
      return "auth.error.signupDisabled";
    default:
      return fallback;
  }
}
