// The rows and nothing else. Loading, the emptinesses and the errors belong to
// the page, as they do in the catalogue and the history: they are the same
// regardless of what the table would have rendered.

import { useI18n } from "@legal-ai/i18n";
import { Badge, Table, TableCell, TableHead, TableRow } from "@legal-ai/ui";
import { Link } from "react-router";
import { formatDateTime } from "../../../shared/format";
import { orderStatusKey } from "../../../shared/vocabulary";
import type { OrderListItem, OrderReviewer } from "../api";
import { statusTone } from "./statusTone";

function Reviewer({ reviewer }: { reviewer: OrderReviewer }) {
  const { t } = useI18n();

  if (reviewer.kind === "person") return <>{reviewer.fullName}</>;

  // Two different absences, and they must not share a rendering (DoD §5).
  // "Nobody has taken this" is work waiting for someone; "somebody has, and
  // you cannot see who" is work already in hand. A dash for both would send a
  // lawyer to pick up a matter a colleague is holding.
  return (
    <span className="text-inkMute">
      {t(reviewer.kind === "none" ? "orders.reviewer.none" : "orders.reviewer.unnamed")}
    </span>
  );
}

export function OrdersTable({ orders }: { orders: OrderListItem[] }) {
  const { t, intlLocale } = useI18n();

  return (
    <Table>
      <TableHead>
        <tr>
          <th>{t("orders.field.client")}</th>
          <th>{t("orders.field.service")}</th>
          <th>{t("orders.field.version")}</th>
          <th>{t("orders.field.status")}</th>
          <th>{t("orders.field.reviewer")}</th>
          <th>{t("orders.field.placed")}</th>
        </tr>
      </TableHead>
      <tbody>
        {orders.map((order) => (
          <TableRow key={order.id}>
            <TableCell>
              {/* The pseudonym is the label and the way in. It is the only
                  thing this screen has ever been given (§7.3) — not a redaction
                  of a name, because `orders` and `clients` hold none — and the
                  only label on the row that names the matter rather than the
                  product it was bought from. */}
              <Link to={`/orders/${order.id}`} className="font-medium text-brand hover:underline">
                {/* check-copy-ignore: a client pseudonym is data, generated by the database */}
                {order.clientPseudonym}
              </Link>
            </TableCell>
            <TableCell>
              <Link to={`/services/${order.serviceId}`} className="text-brand hover:underline">
                {/* check-copy-ignore: a service title is data an admin typed */}
                {order.serviceTitle}
              </Link>
            </TableCell>
            <TableCell>
              {/* The pinned version, not the service's current one. An order
                  placed against v1 still says v1 after two republications —
                  §5.4 as a reader meets it. */}
              {/* check-copy-ignore: a version number is data */}
              <span className="text-inkSoft">{order.version}</span>
            </TableCell>
            <TableCell>
              <div className="flex flex-wrap items-center gap-2">
                <Badge tone={statusTone(order.status)}>{t(orderStatusKey[order.status])}</Badge>
                {order.humanReviewRequested && (
                  // Beside the state rather than inside it, because it does not
                  // replace the state — it changes what the state can become.
                  // `generating` with this set cannot reach `delivered` without
                  // passing through review (Art. 22, ADR-0005).
                  <Badge tone="warn">{t("orders.humanReview")}</Badge>
                )}
              </div>
            </TableCell>
            <TableCell>
              <Reviewer reviewer={order.reviewer} />
            </TableCell>
            <TableCell>{formatDateTime(order.placedAt, intlLocale)}</TableCell>
          </TableRow>
        ))}
      </tbody>
    </Table>
  );
}
